version: "3.7"

networks:
    converter-network:
        driver: bridge

services:
    redis:
        image: redis:6.2.6-alpine
        ports:
            - 6379:6379
        networks:
            - converter-network

    database:
        image: mysql:8.0.27
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - 3306:3306
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
            - MYSQL_DATABASE=${DB_DATABASE}
        networks:
            - converter-network

