version: "3.7"

networks:
  money_converter_network:
    driver: bridge

services:


  mysql:
    image: mysql:8.0.28
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    networks:
      - money_converter_network