version: '3'

services:
  php:
    build:
      context: ./api
      dockerfile: Dockerfile.apache
    container_name: php
    volumes:
      - ./api/backend:/var/www
    ports:
      - 8080:80
  db:
    image: mysql:5.7
    container_name: db
    restart: always
    ports:
      - 3306:3306
    volumes: 
      - ./docker-mysql:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=oliveira_trust
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=danielmn
      - MYSQL_PASSWORD=123456