version: '3.8'

services:
  php:
    build: 
      context: .docker/php/
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
      - "5173:5173"
      - "3001:3000"
    volumes:
      - .:/var/www:cached

  nginx:
    image: nginx
    ports:
      - "61:80"
    volumes:
      - .:/var/www
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  db:
    image: mysql:8.1
    ports:
      - "3306:3306"
    volumes:
      - .docker/db/data:/var/lib/mysql
      - .docker/db/logs:/var/log/mysql
      - .docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - .docker/db/sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lc
      MYSQL_USER: lc
      MYSQL_PASSWORD: lc

  mail:
    image: axllent/mailpit:latest
    ports:
      - "8025:8025"
      - "1025:1025"

  redis:
    image: redis:latest
    command: redis-server --appendonly yes
    volumes:
      - .docker/redis/data:/data
    ports:
      - "638:6379"

