version: '3.1'
services:
  php:
    build: .docker/php
    volumes:
      - ./:/var/www
    depends_on:
      - mysql
      - redis

  nginx:
    build: .docker/nginx
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
    depends_on:
      - php

  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3326:3306"
    volumes:
      - "./.docker/mysql/dbdata:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: oliveiratrust
      MYSQL_ROOT_PASSWORD: root

  redis:
    image: redis:alpine
    expose:
      - 6379
