version: "3.7"

networks:
  money_converter_network:
    driver: bridge

services:

  nginx:
    image: nginx:alpine
    container_name: travellist-nginx
    restart: unless-stopped
    depends_on:
      - money-converter
    ports:
      - 8000:80
    volumes:
      - ./money-converter:/var/www
      - ./.docker/nginx:/etc/nginx/conf.d
    networks:
      - money_converter_network

  money-converter:
    build:
      context: .
      dockerfile: ./money-converter/Dockerfile
    depends_on:
      - redis
      - rabbitmq
      - mysql
    expose:
      - 9000
    volumes:
      - ./money-converter:/var/www
    networks:
      - money_converter_network

  mail-service:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./mail-service/Dockerfile
    depends_on:
      - rabbitmq
    volumes:
      - ./mail-service:/var/www
    networks:
      - money_converter_network

  redis:
    image: redis:6.2.6-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - 6379:6379
    networks:
      - money_converter_network

  rabbitmq:
    image: rabbitmq:3.9.13-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    networks:
      - money_converter_network
    
  mysql:
    image: mysql:8.0.28
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    networks:
      - money_converter_network