version: "3.2"

services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3360:3306
    volumes:
      - .data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=teste
    networks:
      - converter-network
  php:
    build: .
    container_name: desafio_trust
    volumes:
      - ./:/var/www/html
    ports: 
      - 8080:80
    networks:
      - converter-network
    depends_on:
      - mysql
networks:
  converter-network:
    driver: bridge
