services:
  mongodb:
    image: mongo:4.2
    container_name: mongodb_container
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db  # Corrigido para 'mongo_data'

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_container
    ports:
      - "8000:8000"
    environment:
      - MONGO_URL=mongodb://mongodb:27017  # Conexão do MongoDB interna
      - SECRET_KEY=90a3e5hBoep3A1SdTwJZDy7HD3Z1rtKVGgxVBDVUZ24
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30

volumes:
  mongo_data:
    driver: local
