version: "3.2"

services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3360:3306
    volumes:
      - .data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - converter-network
  php:
    build: .
    volumes:
      - ./:/var/www/html
    ports: 
      - 8080:80
    networks:
      - converter-network
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - .redis:/data
    ports:
      - 6379:6379
    networks:
      - converter-network
networks:
  converter-network:
    driver: bridge
