version: '3.9'

services:
  web:
    image: nginx:latest
    ports:
      - "8888:80"
    volumes:
      - ./application:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
    networks:
      - desafio-network
    depends_on:
      - db
      - php

  php:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: desafio-desenvolvedor:1.0
    volumes:
      - ./application:/var/www/html
      - ./docker/entrypoint.sh:/home/root/entrypoint.sh
    networks:
      - desafio-network
    links:
      - db

  db:
    image: mysql:8.1
    command: --default-authentication-plugin=mysql_native_password
    command: --init-file /data/application/init.sql
    volumes:
        - ./database/init.sql:/data/application/init.sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: cakephp
      MYSQL_DATABASE: cakephp
      MYSQL_USER: cakephp
      MYSQL_PASSWORD: cakephp
    ports:
      - "3306:3306"
    networks:
      - desafio-network

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - desafio-network

networks:
  desafio-network:
    driver: bridge