version: '3.1'
services:
  oliveira-db:
    container_name: oliveira_pgslq_db
    image: postgres
    environment:
      POSTGRES_DB: 'dboliveira'
      POSTGRES_PASSWORD: 'root'
      POSTGRES_USER: 'root'
    ports:
      - '5432:5432'
    volumes:
      - ./db/oliveira/pgdata:/var/lib/postgresql/data

  oliveira-api:
    container_name: oliveira_api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 10007:80
    environment:
      APP_ENV: 'local'
      APP_DEBUG: 'true'
      API_URL: 'http://localhost:10007'

      DATABASE_DRIVER: 'pdo_pgsql'
      DATABASE_HOST: oliveira-db
      DATABASE_PORT: '5432'
      DATABASE_NAME: 'dboliveira'
      DATABASE_USER: 'root'
      DATABASE_PASSWORD: 'root'
    
      restart: always
    volumes:
      - ./api:/var/www/html/api
    depends_on:
      - oliveira-db

  oliveira-frontend:
    container_name: oliveira_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV_API=http://localhost:10007
      - NODE_ENV_AMB=dev
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: >
      bash -c "yarn && yarn serve"
    ports:
      - 10008:8080

networks:
  default:
    driver: bridge
