# Generated by Django 5.1 on 2024-09-02 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arquivo',
            name='descricao',
        ),
    ]
