# Generated by Django 5.1 on 2024-09-03 23:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_arquivo_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivo',
            name='upload_arquivo',
            field=models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv', 'xlsx'])]),
        ),
    ]
