# Generated by Django 5.1 on 2024-09-04 02:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_arquivo_upload_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivo',
            name='upload_arquivo',
            field=models.FileField(upload_to='arquivosCSV', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv', 'xlsx'])]),
        ),
    ]
