# Generated by Django 4.2 on 2024-10-04 00:45

import apps.instruments.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('file', models.FileField(unique=True, upload_to=apps.instruments.models.get_file_path)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RptDt', models.CharField(max_length=255)),
                ('TckrSymb', models.CharField(max_length=255)),
                ('Asst', models.CharField(blank=True, max_length=255)),
                ('AsstDesc', models.CharField(blank=True, max_length=255)),
                ('SgmtNm', models.CharField(blank=True, max_length=255)),
                ('MktNm', models.CharField(blank=True, max_length=255)),
                ('SctyCtgyNm', models.CharField(blank=True, max_length=255)),
                ('XprtnDt', models.CharField(blank=True, max_length=255)),
                ('XprtnCd', models.CharField(blank=True, max_length=255)),
                ('TradgStartDt', models.CharField(blank=True, max_length=255)),
                ('TradgEndDt', models.CharField(blank=True, max_length=255)),
                ('BaseCd', models.FloatField(null=True)),
                ('ConvsCritNm', models.CharField(blank=True, max_length=255)),
                ('MtrtyDtTrgtPt', models.FloatField(null=True)),
                ('ReqrdConvsInd', models.CharField(blank=True, max_length=255)),
                ('ISIN', models.CharField(blank=True, max_length=255)),
                ('CFICd', models.CharField(blank=True, max_length=255)),
                ('DlvryNtceStartDt', models.CharField(blank=True, max_length=255)),
                ('DlvryNtceEndDt', models.CharField(blank=True, max_length=255)),
                ('OptnTp', models.CharField(blank=True, max_length=255)),
                ('CtrctMltplr', models.CharField(blank=True, max_length=255)),
                ('AsstQtnQty', models.FloatField(null=True)),
                ('AllcnRndLot', models.IntegerField(null=True)),
                ('TradgCcy', models.CharField(blank=True, max_length=255)),
                ('DlvryTpNm', models.CharField(blank=True, max_length=255)),
                ('WdrwlDays', models.FloatField(null=True)),
                ('WrkgDays', models.FloatField(null=True)),
                ('ClnrDays', models.FloatField(null=True)),
                ('RlvrBasePricNm', models.CharField(blank=True, max_length=255)),
                ('OpngFutrPosDay', models.FloatField(null=True)),
                ('SdTpCd1', models.CharField(blank=True, max_length=255)),
                ('UndrlygTckrSymb1', models.CharField(blank=True, max_length=255)),
                ('SdTpCd2', models.CharField(blank=True, max_length=255)),
                ('UndrlygTckrSymb2', models.CharField(blank=True, max_length=255)),
                ('PureGoldWght', models.FloatField(null=True)),
                ('ExrcPric', models.CharField(blank=True, max_length=255)),
                ('OptnStyle', models.CharField(blank=True, max_length=255)),
                ('ValTpNm', models.CharField(blank=True, max_length=255)),
                ('PrmUpfrntInd', models.CharField(blank=True, max_length=255)),
                ('OpngPosLmtDt', models.CharField(blank=True, max_length=255)),
                ('DstrbtnId', models.FloatField(null=True)),
                ('PricFctr', models.FloatField(null=True)),
                ('DaysToSttlm', models.FloatField(null=True)),
                ('SrsTpNm', models.CharField(blank=True, max_length=255)),
                ('PrtcnFlg', models.CharField(blank=True, max_length=255)),
                ('AutomtcExrcInd', models.CharField(blank=True, max_length=255)),
                ('SpcfctnCd', models.CharField(blank=True, max_length=255)),
                ('CrpnNm', models.CharField(blank=True, max_length=255)),
                ('CorpActnStartDt', models.CharField(blank=True, max_length=255)),
                ('CtdyTrtmntTpNm', models.CharField(blank=True, max_length=255)),
                ('MktCptlstn', models.FloatField(null=True)),
                ('CorpGovnLvlNm', models.CharField(blank=True, max_length=255)),
                ('instrument_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruments.instrumentfile')),
            ],
        ),
    ]
