# Generated by Django 4.2 on 2024-10-04 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instrument',
            options={'verbose_name': 'Instrumento', 'verbose_name_plural': 'Instrumentos'},
        ),
        migrations.AlterModelOptions(
            name='instrumentfile',
            options={'verbose_name': 'Arquivo de Instrumentos', 'verbose_name_plural': 'Arquivos de Instrumentos'},
        ),
    ]
