version: "3"

networks:
    shared:
        driver: bridge
    rabbitmq_shared:
        external: true
    user_shared:
        external: true
    default:

services:
    app:
        build: .
        working_dir: /var/www/
        depends_on:
            - database
            - redis
        volumes:
            - ./src:/var/www
        networks:
            - default
            - shared
            - rabbitmq_shared
            - user_shared


    redis:
        image: redis:latest
        networks:
            - default

    database:
        image: mariadb
        environment:
            MYSQL_DATABASE: homestead
            MYSQL_USER: homestead
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_PASSWORD: secret
        networks:
            - default

    nginx:
        container_name: exchange_api
        image: nginx:alpine
        restart: unless-stopped
        volumes:
            - ./src:/var/www
            - .docker/nginx/conf.d/:/etc/nginx/conf.d/
        depends_on:
            - app
        networks:
            - default
            - shared

    queue:
        build:
            context: .
            dockerfile: Dockerfile
        command: 'php artisan queue:work'
        working_dir: /var/www/
        restart: unless-stopped
        depends_on:
            - app
        volumes:
            - ./src:/var/www
        networks:
            - default
            - rabbitmq_shared
            - user_shared
