version: '3'

services:
  app:
    build: .
    entrypoint: ./.docker/entrypoint.sh
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 3002:3000
    volumes:
      - .:/home/node/app
    tty: true
      