# Generated by Django 5.1 on 2024-08-30 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RptDt', models.DateTimeField()),
                ('TckrSymb', models.CharField(max_length=50)),
                ('MktNm', models.CharField(max_length=50)),
                ('SctyCtgyNm', models.CharField(max_length=50)),
                ('ISIN', models.CharField(max_length=50)),
                ('CrpnNm', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('created_at',),
                'indexes': [models.Index(fields=['-RptDt'], name='fileupload__RptDt_9348c6_idx')],
            },
        ),
    ]
