# Generated by Django 5.1 on 2024-09-03 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='upload_date',
            field=models.DateField(blank=True, default='', null=True),
        ),
    ]
