# Generated by Django 5.1 on 2024-08-31 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='file',
            name='fileupload__RptDt_9348c6_idx',
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['-CrpnNm'], name='fileupload__CrpnNm_ec24c6_idx'),
        ),
    ]
