# Generated by Django 5.1 on 2024-08-31 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0002_remove_file_fileupload__rptdt_9348c6_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ('-RptDt',)},
        ),
        migrations.RemoveIndex(
            model_name='file',
            name='fileupload__CrpnNm_ec24c6_idx',
        ),
        migrations.RemoveField(
            model_name='file',
            name='created_at',
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['-RptDt'], name='fileupload__RptDt_9348c6_idx'),
        ),
    ]
