# Generated by Django 5.1.2 on 2024-10-28 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='uploadhistory',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='uploadhistory',
            name='file_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
