version: "3"

networks:
    user_shared:
        external: true
    exchange_shared:
        external: true
    default:

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: api_gateway
        working_dir: /var/www/
        depends_on:
            - redis
        volumes:
            - ./src:/var/www
        networks:
            - default
            - user_shared
            - exchange_shared

    redis:
        image: redis:latest
        networks:
            - default

    nginx:
        container_name: api_gateway-nginx
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - 8080:80
        volumes:
            - ./src:/var/www
            - .docker/nginx/conf.d/:/etc/nginx/conf.d/
        depends_on:
            - app
        networks:
            - default
            - user_shared
            - exchange_shared
