version: '3'

networks:
  shared:
    driver: bridge
  default:


services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    volumes:
      - .docker/rabbitmq/data:/var/lib/rabbitmq/mnesia
    env_file:
      - messagequeue.env
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - default
      - shared
