<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class Pagamento extends Model
{
    use HasFactory;

    protected $table = 'pagamento';
    public $timestamps = false;
    protected $fillable = ['user_id', 'nome', 'slug', 'taxa'];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::saving(function ($model) {
            $model->slug = Str::slug($model->nome);
            $model->taxa = $model->taxa / 100;
        });
    }
}
