<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Taxa extends Model
{
    use HasFactory;

    protected $table = 'taxa';
    public $timestamps = false;
    protected $fillable = ['user_id', 'valor', 'taxa'];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::saving(function ($model) {
            $model->taxa = $model->taxa / 100;
        });
    }
}
