version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: my_app_image
    container_name: my_app_container
    volumes:
      - .:/var/www/html
    ports:
      - "8000:80"
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: 123456
    entrypoint: ["./entrypoint.sh"]  # Aqui definimos o script de entrada

  db:
    image: mysql:5.7
    container_name: my_db_container
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: laravel
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data:
