[supervisord]
nodaemon=true

[program:apache2]
command=/usr/sbin/apache2ctl -D FOREGROUND
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr

[program:queue-worker]
command=php artisan queue:work --tries=3 --timeout=90
directory=/var/www
autostart=true
autorestart=true
user=www-data
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr